# Generated by Django 5.1.7 on 2025-03-26 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(choices=[('BOT', 'BOT'), ('SET', 'SET'), ('THO', 'THO'), ('TMX', 'TMX'), ('TTC', 'TTC')], max_length=50, unique=True)),
                ('category_name', models.CharField(choices=[('BOT', 'Bột'), ('SET', 'Set trà'), ('THO', 'Trà hoa'), ('TMX', 'Trà mix'), ('TTC', 'Trà củ, quả sấy')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_code', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], max_length=50, unique=True)),
                ('segment_info', models.CharField(choices=[('A1', 'Nhân viên văn phòng, chủ doanh nghiệp (36-45 tuổi) có mức thu nhập cao, thường xuyên tìm hiểu và quan tâm đến sức khoẻ'), ('A2', 'Nhân viên văn phòng, Freelancer ở Miền Bắc (25-35 tuổi) có nhu cầu chăm sóc sức khỏe và quan tâm đến các sản phẩm về trà'), ('A3', 'Sinh viên, nhân viên văn phòng, freelancer (18-24 tuổi) có nhu cầu chăm sóc sức khỏe và quan tâm đến sản phẩm về trà'), ('B1', 'Người làm kinh doanh hoặc văn phòng (45+ tuổi) có thu nhập trung bình có nhu cầu uống trà để hỗ trợ chữa các bệnh nền'), ('B2', 'Người làm nghề nghiệp tự do hoặc nhân viên văn phòng (36-45 tuổi) có nhu cầu uống trà để hỗ trợ chữa các bệnh nền'), ('B3', 'Người làm nghề nghiệp tự do hoặc nhân viên văn phòng (25-35 tuổi) ở Miền Bắc có nhu cầu uống trà để hỗ trợ chữa các bệnh có triệu chứng nhẹ'), ('C1', 'Sinh viên đi làm thêm, nhân viên mới đi làm (20-29 tuổi) có nhu cầu mua làm quà tặng'), ('C2', 'Nhân viên văn phòng, người làm việc tự do (30 - 45 tuổi) ở miền Bắc mua để thử'), ('C3', 'Người mua để uống không có mục đích cụ thể (45+)')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('bill_code', models.CharField(max_length=50, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(choices=[('BOT01', 'BOT01'), ('SET01', 'SET01'), ('SET02', 'SET02'), ('SET03', 'SET03'), ('SET04', 'SET04'), ('SET05', 'SET05'), ('SET06', 'SET06'), ('SET07', 'SET07'), ('THO01', 'THO01'), ('THO02', 'THO02'), ('THO03', 'THO03'), ('THO04', 'THO04'), ('THO05', 'THO05'), ('THO06', 'THO06'), ('TMX01', 'TMX01'), ('TMX02', 'TMX02'), ('TMX03', 'TMX03'), ('TTC01', 'TTC01'), ('TTC02', 'TTC02')], max_length=50, unique=True)),
                ('product_name', models.CharField(choices=[('BOT01', 'Bột cần tây'), ('SET01', 'Set 10 gói trà nụ hoa nhài trắng'), ('SET02', 'Set 10 gói trà hoa đậu biếc'), ('SET03', 'Set 10 gói trà hoa cúc trắng'), ('SET04', 'Set 10 gói trà gừng'), ('SET05', 'Set 10 gói trà dưỡng nhan'), ('SET06', 'Set 10 gói trà gạo lứt 8 vị'), ('SET07', 'Set 10 gói trà cam sả quế'), ('THO01', 'Trà nụ hoa nhài trắng'), ('THO02', 'Trà hoa đậu biếc'), ('THO03', 'Trà hoa cúc trắng'), ('THO04', 'Trà nụ hoa hồng Tây Tạng'), ('THO05', 'Trà hoa Atiso'), ('THO06', 'Trà nhuỵ hoa nghệ tây'), ('TMX01', 'Trà dưỡng nhan'), ('TMX02', 'Trà cam sả quế'), ('TMX03', 'Trà gạo lứt 8 vị'), ('TTC01', 'Trà gừng'), ('TTC02', 'Cam lát')], max_length=255)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.category')),
            ],
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.segment'),
        ),
    ]
